dist: trusty
language: python
python:
  #- '2.7'
  - '3.6'
before_install:
  - pip install codecov
  - pip install pipenv
install:
  - pipenv install --dev
script:
  - pipenv run pytest --cov=falcon_pagination_processor tests
  - if [ "$TRAVIS_BRANCH" == "master" ]; then codecov; fi
deploy:
  provider: pypi
  user: neetjn
  password:
    secure: EgtIN1gktMh3pk72NK2SY/sOqDzSb/vSagCZw7IMqIQMS5bePbK7rTN9cLp5I6FsAem7210+kJ95pQibNZfKGPYhD0wpPLboScyJpXNOL3LybRJ2sgSxEwmDI77XUHfnLrYd8wvxzGljNEaAafF6rRscksIkPR4CK1SCiWVU38MW3F47meS0NUgSDKRpnhlBgW/ee7RhFwOC7m8IgAreR5fETG5Zcg2UN7z38PGLwiRCD8lbr2w5qlXqBuTa05cXPBoEMXpUGqQ9eRl1NPZJTgXrC7B2YHMATyDheEkaeu9j7wFPBkkNJOpnv2S/qW9JA8wTbyzYcSsCCB0jGIf1OAHWR75PcN+lBi3CQK/kepSbVj1SIHJXXpu8CBS1eO0TkEvNJvJ91Ql5bnIYt6loW5yLa/4tFdWhtyP4kHIdSLPcSujr/SDXUuVxsKqCGk4uvi5T7rfYJhfzGVy9rmiBsMKbQo8uROUb9ozbr2ugKqh+98+Y8SYltCUvwo7QcX3jZdHzBcpFcT+JGSrgFbRu/us7IK4mDBD7wH96tDhVxDRYk74kyqvEtuwXade2fJ11MwEjjiKyZ/XUxQ5UaOvWyWcMD4UbFItAw4ts1bsyMCEsO3JfMwIIDtrDkD9n1nkPFK0p0ja+CDkfvI0xnV+Zkw9DJBLViNBRJP3UpqJpdaA=
  on:
    branch: master
